#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate translation-sample.txt from tinyfilemanager.php.

Expected directory structure:

project/
├── tinyfilemanager.php
└── samples/
    ├── generate_translation-sample.py
    └── translation-sample.txt

Usage:
    python generate_translation-sample.py
"""

from __future__ import annotations

import datetime
import json
import pathlib
import re
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
SOURCE_FILE = SCRIPT_DIR.parent / "tinyfilemanager.php"
OUTPUT_FILE = SCRIPT_DIR / "translation-sample.txt"

HEADER = """/**************************************************************************
 * THIS FILE IS AUTO-GENERATED.
 * DO NOT EDIT IT MANUALLY.
 *
 * This is a sample to be used by "sync_translations.py".
 *
 * Generated by:
 *     python generate_translation-sample.py
 *
 * Source: ../tinyfilemanager.php
 * Generated on: @TIMESTAMP@
 *
 * Note: this is not a valid JSON comment. JSON does not support comments.
 **************************************************************************/"""

PATTERN = re.compile(
    r"""\$tr\['en'\]\['((?:\\.|[^'])*)'\]\s*=\s*'((?:\\.|[^'])*)';"""
)


def unescape_php(text: str) -> str:
    """
    Decode common PHP single-quoted string escapes.
    """
    return text.replace(r"\\", "\\").replace(r"\'", "'")


def main() -> int:
    if not SOURCE_FILE.exists():
        print(f"ERROR: Source file not found: {SOURCE_FILE}", file=sys.stderr)
        return 1

    print(f"Reading {SOURCE_FILE.relative_to(SCRIPT_DIR.parent)}...")

    source = SOURCE_FILE.read_text(encoding="utf-8")

    translations = {}

    for key, value in PATTERN.findall(source):
        translations[unescape_php(key)] = unescape_php(value)

    if not translations:
        print("ERROR: No translation strings found.", file=sys.stderr)
        return 1

    ordered = dict(sorted(translations.items(), key=lambda item: item[0].casefold()))

    data = {
        "name": "English",
        "code": "en",
        "translation": ordered,
    }

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header = HEADER.replace("@TIMESTAMP@", timestamp)

    json_text = json.dumps(
        data,
        indent=4,
        ensure_ascii=False,
    )

    OUTPUT_FILE.write_text(
        header + "\n\n" + json_text + "\n",
        encoding="utf-8",
    )

    print(f"Found {len(ordered)} translation strings.")
    print(f"Writing {OUTPUT_FILE.name}...")
    print("Done.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
